name: flux
description: "Flux: The habit changer"
publish_to: "none"

version: 2.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4

  table_calendar: ^3.0.9
  share_plus: ^12.0.1
  csv: ^6.0.0
  syncfusion_flutter_charts: ^31.2.12
  collection: ^1.18.0

  flutter_local_notifications: ^19.5.0
  home_widget: ^0.8.1
  uuid: ^4.5.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  confetti: ^0.8.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.2
  file_picker: ^10.3.7

  sqflite: ^2.3.2
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.3

  timezone: ^0.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "icons/icon.png"
  image_path: "icons/icon.png"
